# Generated by Django 6.0.6 on 2026-07-15 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0029_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_reference', models.CharField(editable=False, max_length=100, unique=True)),
                ('gateway_reference', models.CharField(blank=True, help_text='Paystack transaction ID', max_length=200, null=True)),
                ('amount_accommodation', models.DecimalField(decimal_places=2, help_text='Amount going to landlord', max_digits=10)),
                ('amount_platform_fee', models.DecimalField(decimal_places=2, help_text='StayMatch commission (5%)', max_digits=10)),
                ('amount_total', models.DecimalField(decimal_places=2, help_text='Total charged to user', max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('payment_method', models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('vodafone_cash', 'Vodafone Cash'), ('airteltigo_money', 'AirtelTigo Money'), ('card_visa', 'Visa Card'), ('card_mastercard', 'Mastercard'), ('card_verve', 'Verve Card'), ('bank_transfer', 'Bank Transfer')], max_length=30, null=True)),
                ('payment_status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='initiated', max_length=30)),
                ('attempt_count', models.IntegerField(default=0, help_text='Number of payment attempts')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_window_opens_at', models.DateTimeField(help_text='When payment window opens')),
                ('payment_window_closes_at', models.DateTimeField(help_text='2-hour payment deadline')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was successfully completed', null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Full Paystack response', null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('refund_completed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_gateway_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('refund_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('disbursed_to_landlord', models.BooleanField(default=False)),
                ('disbursement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='bookings.booking')),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staymatch_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking'], name='staymatch_p_booking_0f8c0c_idx'), models.Index(fields=['user'], name='staymatch_p_user_id_3714a3_idx'), models.Index(fields=['payment_status'], name='staymatch_p_payment_5b8e59_idx'), models.Index(fields=['payment_window_closes_at'], name='idx_payment_window_close')],
            },
        ),
    ]
