# Generated by Django 6.0.6 on 2026-06-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='aspects_highlighted',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='review',
            name='concerns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='review',
            name='guest_type',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('WORKER', 'Worker'), ('FAMILY', 'Family'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='not_helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('DEFINITELY', 'Yes, definitely'), ('MAYBE', 'Maybe'), ('NO', 'No, not recommended')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='stay_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='stay_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='trust_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='verification_level',
            field=models.CharField(choices=[('VERIFIED_GUEST', 'Verified Guest'), ('VERIFIED_THIRD_PARTY', 'Verified via Third Party'), ('UNVERIFIED', 'Unverified')], default='UNVERIFIED', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='would_stay_again',
            field=models.CharField(blank=True, choices=[('ALREADY_BOOKED', 'Already booked next semester'), ('DEFINITELY', 'Definitely'), ('MAYBE', 'Maybe'), ('NO', 'No, looking elsewhere')], max_length=30, null=True),
        ),
    ]
