# Generated by Django 6.0.6 on 2026-06-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='business_registration_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant_type',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('WORKER', 'Worker'), ('FAMILY', 'Family'), ('COUPLE', 'Couple'), ('SINGLE_PROFESSIONAL', 'Single Professional'), ('NATIONAL_SERVICE', 'National Service Personnel'), ('EXPATRIATE', 'Expatriate'), ('SHORT_STAY', 'Short-Stay Guest')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('ADMIN', 'Admin')], default='TENANT', max_length=10),
        ),
    ]
