# Generated by Django 6.0.6 on 2026-06-16 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='budget_min',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cleanliness_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_pets',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_smoker',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_move_in_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sleep_schedule',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='social_preference',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='study_habits',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='household_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='LifestyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_schedule', models.CharField(blank=True, choices=[('EARLY_BIRD', 'Early Bird (Sleeps early)'), ('MODERATE', 'Moderate'), ('NIGHT_OWL', 'Night Owl (Sleeps late)')], max_length=20)),
                ('wake_time', models.CharField(blank=True, choices=[('EARLY', 'Early (Before 7 AM)'), ('MODERATE', 'Moderate (7-9 AM)'), ('LATE', 'Late (After 9 AM)')], max_length=20)),
                ('cleanliness_level', models.PositiveIntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], null=True)),
                ('study_habits', models.CharField(blank=True, choices=[('QUIET_ENVIRONMENT', 'Needs Quiet Environment'), ('STUDY_LATE', 'Studies Late'), ('GROUP_STUDY', 'Prefers Group Study'), ('WORK_FROM_HOME', 'Works From Home')], max_length=50)),
                ('social_personality', models.CharField(blank=True, choices=[('INTROVERT', 'Introvert'), ('EXTROVERT', 'Extrovert'), ('BALANCED', 'Balanced')], max_length=20)),
                ('visitor_preference', models.CharField(blank=True, choices=[('FREQUENTLY', 'Frequently'), ('OCCASIONALLY', 'Occasionally'), ('RARELY', 'Rarely'), ('NEVER', 'Never')], max_length=20)),
                ('noise_tolerance', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('smoking_comfortable', models.BooleanField(blank=True, null=True)),
                ('drinking_comfortable', models.BooleanField(blank=True, null=True)),
                ('gender_preference', models.CharField(blank=True, choices=[('MALE', 'Male Only'), ('FEMALE', 'Female Only'), ('ANY', 'No Preference')], max_length=20)),
                ('additional_notes', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lifestyle Profile',
                'verbose_name_plural': 'Lifestyle Profiles',
                'db_table': 'lifestyle_profiles',
            },
        ),
    ]
