# Generated by Django 6.0.6 on 2026-06-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginattempt_rename_is_verified_user_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
