# Generated by Django 6.0.6 on 2026-06-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_emailverification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
