# Generated by Django 6.0.6 on 2026-06-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20260617_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('private', 'Private (matched roommates only)'), ('public', 'Public (all users)'), ('hidden', 'Hidden (no one)')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
