# Generated by Django 6.0.6 on 2026-06-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_data_sharing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
