# Generated by Django 6.0.6 on 2026-06-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_deletion_scheduled_date_user_is_deactivated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifestyleprofile',
            old_name='additional_notes',
            new_name='additional_concerns',
        ),
        migrations.RenameField(
            model_name='lifestyleprofile',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='cleanliness_level',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='drinking_comfortable',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='gender_preference',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='sleep_schedule',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='smoking_comfortable',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='social_personality',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='study_habits',
        ),
        migrations.RemoveField(
            model_name='lifestyleprofile',
            name='visitor_preference',
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='air_con_preference',
            field=models.CharField(blank=True, choices=[('FAN', 'Fan only'), ('AC', 'AC only'), ('BOTH', 'Both fan and AC')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='alcohol_tolerance',
            field=models.CharField(blank=True, choices=[('NO', 'No drinking'), ('OCCASIONAL', 'Occasional okay'), ('REGULAR', 'Regular okay')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='comfort_with_opposite_gender_visitors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='cooking_frequency',
            field=models.CharField(blank=True, choices=[('NEVER', 'Never'), ('RARELY', 'Rarely'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='dietary_restrictions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='entertainment_noise_preference',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='food_sharing_comfort',
            field=models.CharField(blank=True, choices=[('ALWAYS', 'Always okay'), ('ASK_FIRST', 'Ask first'), ('NEVER', 'Never')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='guest_entertainment_location',
            field=models.CharField(blank=True, choices=[('ROOM', 'In room'), ('COMMON_AREA', 'Common area only'), ('OUTSIDE', 'Outside property')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='guest_type',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('WORKER', 'Worker'), ('FAMILY', 'Family'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='night_activity_level',
            field=models.CharField(choices=[('MINIMAL', 'Minimal (quiet after 10pm)'), ('MODERATE', 'Moderate'), ('ACTIVE', 'Active')], default='MINIMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='personal_cleanliness_level',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='personal_space_importance',
            field=models.CharField(blank=True, choices=[('IMPORTANT', 'Important'), ('MODERATE', 'Moderate'), ('FLEXIBLE', 'Flexible')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='preferred_noise_level',
            field=models.CharField(blank=True, choices=[('QUIET', 'Quiet'), ('MODERATE', 'Moderate'), ('SOCIAL', 'Social/Active')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='preferred_temperature',
            field=models.IntegerField(blank=True, help_text='Celsius', null=True),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='privacy_preference',
            field=models.CharField(blank=True, choices=[('LOW', 'Low - open door policy'), ('MODERATE', 'Moderate'), ('HIGH', 'High - need privacy')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='quiet_hours_needed',
            field=models.CharField(blank=True, choices=[('AFTER_9PM', 'After 9pm'), ('AFTER_10PM', 'After 10pm'), ('AFTER_11PM', 'After 11pm'), ('NO_RESTRICTION', 'No restriction')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='shared_expense_comfort',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='shared_items_comfort',
            field=models.CharField(blank=True, choices=[('ALWAYS', 'Always okay'), ('ASK_FIRST', 'Ask first'), ('NEVER', 'Never')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='shared_kitchen_comfort',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='shared_space_cleaning_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='sleep_time',
            field=models.CharField(blank=True, choices=[('VERY_EARLY', 'Very early (before 9pm)'), ('EARLY', 'Early (9-10pm)'), ('MODERATE', 'Moderate (10-11pm)'), ('LATE', 'Late (after 11pm)')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='sleep_time_details',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='smoking_tolerance',
            field=models.CharField(blank=True, choices=[('NON_SMOKER', 'Non-smoker only'), ('OCCASIONAL', 'Occasional okay'), ('SMOKER', 'Smoker okay')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='social_study_preference',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('DEPENDS', 'Depends')], default='NO', max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='special_food_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='study_location',
            field=models.CharField(blank=True, choices=[('ROOM', 'In room'), ('OUTSIDE', 'Outside (library/cafe)'), ('LIBRARY', 'Library')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='study_noise_preference',
            field=models.CharField(blank=True, choices=[('QUIET', 'Quiet needed'), ('LOW_MUSIC', 'Low music okay'), ('ANY', 'Any noise okay')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='study_time',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('DAY', 'Day'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='study_with_music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='temperature_range',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='toilet_cleaning_responsibility',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='uses_alarm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='visitor_frequency',
            field=models.CharField(blank=True, choices=[('RARE', 'Rare (few times per semester)'), ('OCCASIONAL', 'Occasional (monthly)'), ('FREQUENT', 'Frequent (weekly)')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='visitor_overnight_preference',
            field=models.CharField(blank=True, choices=[('NO', 'No overnight guests'), ('NOTICE_24H', '24-hour notice'), ('NOTICE_48H', '48-hour notice'), ('FLEXIBLE', 'Flexible')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='wake_time_details',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='window_open_preference',
            field=models.CharField(blank=True, choices=[('ALWAYS', 'Always open'), ('SOMETIMES', 'Sometimes'), ('NEVER', 'Never')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='noise_tolerance',
            field=models.CharField(blank=True, choices=[('LOW', 'Low - need quiet'), ('MODERATE', 'Moderate'), ('HIGH', 'High - okay with noise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='wake_time',
            field=models.CharField(blank=True, choices=[('VERY_EARLY', 'Very early (before 6am)'), ('EARLY', 'Early (6-7am)'), ('MODERATE', 'Moderate (7-8am)'), ('LATE', 'Late (after 8am)')], max_length=20),
        ),
    ]
