# Generated by Django 6.0.6 on 2026-06-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_notif_booking_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyleprofile',
            name='conflict_resolution_preference',
            field=models.CharField(blank=True, choices=[('DIRECT', 'Direct conversation'), ('MEDIATOR', 'Mediator/third party'), ('SPACE', 'Give space first'), ('ADMIN', 'Admin involvement')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='conflict_style',
            field=models.CharField(blank=True, choices=[('CALM', 'Calm and reasonable'), ('DIRECT_RESPECTFUL', 'Direct but respectful'), ('TAKES_TIME', 'Takes time to cool off'), ('AVOID', 'Avoid confrontation')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='visitor_notice_preference',
            field=models.CharField(blank=True, choices=[('NO_NOTICE', 'No notice needed'), ('SHORT_NOTICE', 'Any notice appreciated'), ('NOTICE_24H', '24-48 hours notice preferred')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='visitor_overnight_preference',
            field=models.CharField(blank=True, choices=[('NO', 'No overnight guests'), ('RARELY', 'Rarely'), ('SOMETIMES', 'Sometimes'), ('FREQUENTLY', 'Frequently')], max_length=20),
        ),
    ]
