# Generated by Django 6.0.6 on 2026-06-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_lifestyleprofile_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'System Alert'), ('BOOKING_UPDATE', 'Booking Update'), ('MATCH_FOUND', 'Roommate Match Found'), ('PAYMENT', 'Payment Alert'), ('MESSAGE', 'New Message'), ('CONFLICT', 'Conflict Report Update')], default='SYSTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
