# Generated by Django 6.0.6 on 2026-06-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyleprofile',
            name='privacy_meaning',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='quiet_hours_still_needed',
            field=models.CharField(blank=True, choices=[('YES', 'Yes, definitely — even when studying outside, I need quiet to sleep'), ('SOMEWHAT', 'Somewhat — some quiet is helpful'), ('NOT_REALLY', 'Not really — I can manage with noise'), ('NO', 'No — I study elsewhere and am not in the room much')], max_length=20),
        ),
        migrations.AddField(
            model_name='lifestyleprofile',
            name='quiet_times',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='air_con_preference',
            field=models.CharField(blank=True, choices=[('FAN', 'Fan preferred'), ('AC', 'Air conditioning if available'), ('BOTH', 'Both depending on weather'), ('NONE', 'No preference')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='conflict_resolution_preference',
            field=models.CharField(blank=True, choices=[('DIRECT', 'Direct conversation — I prefer talking it out calmly'), ('MEDIATOR', 'Mediator — I would like someone neutral to help'), ('SPACE', 'Give space — I prefer time before discussing'), ('ADMIN', 'Admin — I would involve property management')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='cooking_frequency',
            field=models.CharField(blank=True, choices=[('NEVER', "Never — I don't cook"), ('WEEKLY', 'Weekly — I cook 1-3 times per week'), ('FREQUENTLY', 'Frequently — 4-5 times per week'), ('DAILY', 'Daily — I cook most days')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='night_activity_level',
            field=models.CharField(choices=[('MINIMAL', 'Minimal — Usually in bed or completely quiet'), ('MODERATE', 'Moderate — Some activity like quiet studying'), ('ACTIVE', 'Active — I study, watch content, or socialize at night'), ('VERY_ACTIVE', 'Very Active — I often have guests or stay busy late')], default='MINIMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='noise_tolerance',
            field=models.CharField(blank=True, choices=[('LOW', 'Low — I need quiet to sleep and study. Noise is very disruptive.'), ('MODERATE', 'Moderate — Some noise is fine but not late at night'), ('HIGH', 'High — I am not easily bothered by noise'), ('VERY_HIGH', 'Very High — Noise does not bother me at all')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='personal_space_importance',
            field=models.CharField(blank=True, choices=[('VERY_IMPORTANT', 'Very Important — I value my space and personal time highly'), ('IMPORTANT', 'Important — privacy matters but I am flexible'), ('SOMEWHAT', 'Somewhat — some privacy is nice but not critical'), ('NOT_IMPORTANT', 'Not Important — I am very social and open')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='preferred_noise_level',
            field=models.CharField(blank=True, choices=[('QUIET', 'Quiet — Generally quiet, minimal background noise okay'), ('VERY_QUIET', 'Very Quiet — Complete silence at all times'), ('MODERATE', 'Moderate — Some activity and conversation is fine'), ('LIVELY', 'Lively — I like an active, social atmosphere')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='shared_items_comfort',
            field=models.CharField(blank=True, choices=[('ALWAYS', 'Always — we can freely share'), ('ASK_FIRST', 'Ask First — I am okay with sharing if they ask'), ('RARELY', 'Rarely — I prefer minimal borrowing'), ('NEVER', 'Never — I prefer not to share my things')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='shared_kitchen_comfort',
            field=models.CharField(blank=True, choices=[('YES', 'Yes, totally — we can coordinate schedules'), ('SET_TIMES', 'Yes, but I prefer set times'), ('MINIMAL', 'Minimal — prefer limited kitchen interaction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='shared_space_cleaning_frequency',
            field=models.CharField(blank=True, choices=[('RARELY', 'Rarely (once a month or less)'), ('WEEKLY', 'Weekly (once a week or as needed)'), ('VERY_FREQUENT', 'Very Frequently (2-3 times per week)'), ('OBSESSIVE', 'Obsessively (deep clean multiple times per week)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='sleep_time',
            field=models.CharField(blank=True, choices=[('VERY_EARLY', 'Very Early — Before 9pm'), ('EARLY', 'Early — Around 9-10pm'), ('MODERATE', 'Moderate — Around 10-11pm'), ('LATE', 'Late — After 11pm'), ('VERY_LATE', 'Very Late — Midnight or later')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='study_location',
            field=models.CharField(blank=True, choices=[('OUTSIDE', 'Mainly Outside — Library, cafe, or on campus'), ('MIXED', 'Mixed — Both in room and outside'), ('ROOM', 'Mainly in Room — I prefer studying in my room')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='uses_alarm',
            field=models.CharField(blank=True, choices=[('YES', 'Yes, I rely on an alarm'), ('NO', 'No, I wake naturally'), ('SOMETIMES', 'Sometimes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='visitor_frequency',
            field=models.CharField(blank=True, choices=[('RARE', 'Rarely (few times a semester or less)'), ('OCCASIONAL', 'Occasionally (monthly or a few times per month)'), ('FREQUENT', 'Frequently (weekly)'), ('VERY_FREQUENT', 'Very Frequently (multiple times per week)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='visitor_notice_preference',
            field=models.CharField(blank=True, choices=[('NOTICE_24H', 'Yes — 24-48 hours notice preferred'), ('SHORT_NOTICE', 'Yes — any notice appreciated'), ('NO_NOTICE', 'No — guests are fine anytime')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='visitor_overnight_preference',
            field=models.CharField(blank=True, choices=[('NEVER', 'Never — only daytime visits'), ('RARELY', 'Rarely — occasional overnight, but rare'), ('SOMETIMES', 'Sometimes — yes, sometimes overnight'), ('FREQUENTLY', 'Frequently — guests often stay overnight')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyleprofile',
            name='wake_time',
            field=models.CharField(blank=True, choices=[('VERY_EARLY', 'Very Early — Before 6am'), ('EARLY', 'Early — Around 6-7am'), ('MODERATE', 'Moderate — Around 7-8am'), ('LATE', 'Late — Around 8-9am'), ('VERY_LATE', 'Very Late — After 9am')], max_length=20),
        ),
    ]
