# Generated by Django 6.0.6 on 2026-06-16 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('SAFETY', 'Safety'), ('UTILITIES', 'Utilities'), ('INTERNET', 'Internet'), ('KITCHEN', 'Kitchen'), ('BATHROOM', 'Bathroom'), ('LAUNDRY', 'Laundry'), ('OUTDOOR', 'Outdoor'), ('STUDY', 'Study')], default='GENERAL', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'db_table': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Type',
                'verbose_name_plural': 'Property Types',
                'db_table': 'property_types',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('HOSTEL', 'Hostel'), ('APARTMENT', 'Apartment'), ('SHARED_ROOM', 'Shared Room'), ('PRIVATE_ROOM', 'Private Room'), ('ENTIRE_PLACE', 'Entire Place')], default='APARTMENT', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_rooms', models.PositiveIntegerField(default=1)),
                ('total_bathrooms', models.PositiveIntegerField(default=1)),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Area in square meters', max_digits=10)),
                ('floor_number', models.PositiveIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.DateField()),
                ('minimum_stay_months', models.PositiveIntegerField(default=1)),
                ('maximum_stay_months', models.PositiveIntegerField(blank=True, null=True)),
                ('house_rules', models.TextField(blank=True)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('guests_allowed', models.BooleanField(default=True)),
                ('maximum_guests', models.PositiveIntegerField(default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('inquiries_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('accommodation_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.amenity')),
            ],
            options={
                'db_table': 'property_amenities',
                'unique_together': {('accommodation_property', 'amenity')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(related_name='properties', through='properties.PropertyAmenity', through_fields=('accommodation_property', 'amenity'), to='properties.amenity'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('image_type', models.CharField(choices=[('EXTERIOR', 'Exterior'), ('INTERIOR', 'Interior'), ('ROOM', 'Room'), ('BATHROOM', 'Bathroom'), ('KITCHEN', 'Kitchen'), ('AMENITY', 'Amenity'), ('FLOOR_PLAN', 'Floor Plan'), ('OTHER', 'Other')], default='INTERIOR', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'db_table': 'property_images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.propertytype'),
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='property_videos/')),
                ('video_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_virtual_tour', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Video',
                'verbose_name_plural': 'Property Videos',
                'db_table': 'property_videos',
            },
        ),
        migrations.CreateModel(
            name='PropertyViewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_viewings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Viewing',
                'verbose_name_plural': 'Property Viewings',
                'db_table': 'property_viewings',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single Room'), ('DOUBLE', 'Double Room'), ('SHARED', 'Shared Room'), ('STUDIO', 'Studio'), ('MASTER', 'Master Bedroom'), ('DORM', 'Dormitory')], default='SINGLE', max_length=20)),
                ('bed_type', models.CharField(choices=[('SINGLE', 'Single Bed'), ('DOUBLE', 'Double Bed'), ('QUEEN', 'Queen Bed'), ('KING', 'King Bed'), ('BUNK', 'Bunk Bed'), ('FUTON', 'Futon')], default='SINGLE', max_length=20)),
                ('max_occupancy', models.PositiveIntegerField(default=1)),
                ('current_occupancy', models.PositiveIntegerField(default=0)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in square meters', max_digits=10)),
                ('has_private_bathroom', models.BooleanField(default=False)),
                ('has_private_kitchen', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=False)),
                ('has_desk', models.BooleanField(default=False)),
                ('has_wardrobe', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['room_number'],
                'unique_together': {('accommodation_property', 'room_number')},
            },
        ),
    ]
