# Generated by Django 6.0.6 on 2026-06-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_savedproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='prohibited_items',
            field=models.TextField(blank=True, help_text='Comma-separated list of prohibited items (e.g. rice cooker, heater, pets, musical instruments)'),
        ),
    ]
