# Generated by Django 6.0.6 on 2026-06-24 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProximityDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=200)),
                ('destination_type', models.CharField(choices=[('INSTITUTION', 'Institution'), ('MARKET', 'Market'), ('PHARMACY', 'Pharmacy'), ('TRANSPORT', 'Transport Hub'), ('ATM', 'ATM/Bank'), ('HOSPITAL', 'Hospital'), ('RESTAURANT', 'Restaurant'), ('SHOPPING', 'Shopping Mall'), ('OTHER', 'Other')], max_length=50)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers', max_digits=5, null=True)),
                ('travel_time_minutes', models.PositiveIntegerField(blank=True, help_text='Travel time in minutes', null=True)),
                ('travel_mode', models.CharField(choices=[('WALK', 'Walk'), ('DRIVE', 'Drive'), ('TROTRO', 'Trotro'), ('BUS', 'Bus'), ('TAXI', 'Taxi')], default='WALK', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('accommodation_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proximity_destinations', to='properties.property')),
            ],
            options={
                'verbose_name': 'Proximity Destination',
                'verbose_name_plural': 'Proximity Destinations',
                'db_table': 'proximity_destinations',
                'ordering': ['order'],
            },
        ),
    ]
