# Generated by Django 6.0.6 on 2026-06-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_proximitydestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='billing_model',
            field=models.CharField(choices=[('SEMESTER_BASED', 'Semester-Based'), ('MONTHLY_BASED', 'Monthly-Based'), ('ANNUAL_BASED', 'Annual-Based'), ('ACADEMIC_YEAR', 'Academic Year (Combined 2-Semester)')], default='SEMESTER_BASED', max_length=20),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='academic_year_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Combined 2-semester price with discount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='allow_two_year_advance',
            field=models.BooleanField(default=False, help_text='Allow 2-year advance payment for Annual-Based'),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='early_checkout_allowed',
            field=models.BooleanField(default=True, help_text='Allow early checkout for Annual-Based'),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='early_checkout_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Penalty amount for early checkout', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='max_months',
            field=models.PositiveIntegerField(default=12, help_text='Maximum months bookable at once'),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='max_semesters',
            field=models.PositiveIntegerField(default=3, help_text='Maximum semesters bookable at once (1-3)'),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='min_months',
            field=models.PositiveIntegerField(default=1, help_text='Minimum months for monthly booking'),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='two_years_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='2-year advance payment price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unittype',
            name='billing_model',
            field=models.CharField(choices=[('SEMESTER_BASED', 'Semester-Based'), ('MONTHLY_BASED', 'Monthly-Based'), ('ANNUAL_BASED', 'Annual-Based'), ('ACADEMIC_YEAR', 'Academic Year (Combined 2-Semester)')], default='MONTHLY_BASED', max_length=20),
        ),
        migrations.AddField(
            model_name='unittypepricing',
            name='academic_year_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Combined 2-semester price with discount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unittypepricing',
            name='allow_two_year_advance',
            field=models.BooleanField(default=False, help_text='Allow 2-year advance payment for Annual-Based'),
        ),
        migrations.AddField(
            model_name='unittypepricing',
            name='early_checkout_allowed',
            field=models.BooleanField(default=True, help_text='Allow early checkout for Annual-Based'),
        ),
        migrations.AddField(
            model_name='unittypepricing',
            name='early_checkout_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Penalty amount for early checkout', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unittypepricing',
            name='max_months',
            field=models.PositiveIntegerField(default=12, help_text='Maximum months bookable at once'),
        ),
        migrations.AddField(
            model_name='unittypepricing',
            name='max_semesters',
            field=models.PositiveIntegerField(default=3, help_text='Maximum semesters bookable at once (1-3)'),
        ),
        migrations.AddField(
            model_name='unittypepricing',
            name='min_months',
            field=models.PositiveIntegerField(default=1, help_text='Minimum months for monthly booking'),
        ),
    ]
