# Generated by Django 6.0.6 on 2026-06-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_roomtype_billing_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtypepricing',
            name='allow_monthly_extensions',
            field=models.BooleanField(default=False, help_text='Allow monthly extensions for this room type'),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=7, help_text='Grace period duration in days (3-14)'),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='monthly_extension_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rate for extensions', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtypepricing',
            name='overstay_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Overstay rate multiplier (1.0-2.0)', max_digits=3),
        ),
        migrations.AddField(
            model_name='unittypepricing',
            name='allow_monthly_extensions',
            field=models.BooleanField(default=False, help_text='Allow monthly extensions for this room type'),
        ),
        migrations.AddField(
            model_name='unittypepricing',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=7, help_text='Grace period duration in days (3-14)'),
        ),
        migrations.AddField(
            model_name='unittypepricing',
            name='monthly_extension_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rate for extensions', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unittypepricing',
            name='overstay_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Overstay rate multiplier (1.0-2.0)', max_digits=3),
        ),
    ]
