# Generated by Django 6.0.6 on 2026-06-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_roomtypepricing_allow_monthly_extensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PARTIALLY_OCCUPIED', 'Partially Occupied'), ('OCCUPIED', 'Occupied (Single — slots remain)'), ('FULLY_OCCUPIED', 'Fully Occupied'), ('VACATION_RESERVE', 'Vacation Reserve — Held for Student'), ('PRACTICAL_CHECKOUT', 'Practical Checkout (48h, Split Stay)'), ('GRACE_PERIOD', 'Grace Period'), ('OVERSTAY', 'Overstay — Student Not Vacated'), ('MAINTENANCE', 'Maintenance — Temporarily Unavailable'), ('ARCHIVED', 'Archived — Removed from Listings'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20),
        ),
    ]
