# Generated by Django 6.0.7 on 2026-07-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_update_image_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('image_type', models.CharField(choices=[('BEDROOM', 'Bedroom/Interior'), ('WASHROOM', 'Washroom'), ('KITCHEN', 'Kitchen'), ('OTHER', 'Other')], default='BEDROOM', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.room')),
            ],
        ),
    ]
