# Generated by Django 6.0.7 on 2026-08-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_seed_single_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Direct Contact Email of Owner', max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Full Name of Property Manager / Owner', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(blank=True, help_text='Direct Phone / WhatsApp Number of Owner', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_photo',
            field=models.ImageField(blank=True, help_text='Profile Photo of Property Manager / Owner', null=True, upload_to='property_managers/'),
        ),
    ]
