# Generated by Django 6.0.6 on 2026-06-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='room',
        ),
    ]
