# Generated by Django 6.0.6 on 2026-06-16 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_room_remove_bookingrequest_room'),
        ('properties', '0002_rename_inquiries_count_property_booking_requests_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.roomtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.unittype'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='properties.roomtype'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='properties.unittype'),
        ),
    ]
