# Generated by Django 6.0.6 on 2026-06-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_room_type_booking_unit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lifestyle_assessment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='lifestyle_assessment_required',
            field=models.BooleanField(default=False),
        ),
    ]
