# Generated by Django 6.0.6 on 2026-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_lifestyle_assessment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommatematch',
            name='cleanliness_compatibility',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='roommatematch',
            name='noise_compatibility',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='roommatematch',
            name='sleep_compatibility',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='roommatematch',
            name='social_compatibility',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
