# Generated by Django 6.0.6 on 2026-06-17 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_roommatematch_cleanliness_compatibility_and_more'),
        ('properties', '0003_savedproperty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('room_type', models.CharField(blank=True, max_length=50)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Search',
                'verbose_name_plural': 'Property Searches',
                'db_table': 'property_searches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='property_se_user_id_03fac9_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recently Viewed',
                'verbose_name_plural': 'Recently Viewed',
                'db_table': 'recently_viewed',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='recently_vi_user_id_ec1573_idx')],
                'unique_together': {('user', 'property')},
            },
        ),
    ]
