# Generated by Django 6.0.6 on 2026-06-17 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_propertysearch_recentlyviewed'),
        ('properties', '0003_savedproperty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='consent_timeout_date',
            field=models.DateTimeField(blank=True, help_text='Deadline for user to respond', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='roommate_consent',
            field=models.BooleanField(default=False, help_text='Roommate accepted the match'),
        ),
        migrations.AddField(
            model_name='booking',
            name='roommate_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_consent',
            field=models.BooleanField(default=False, help_text='User accepted the match'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('COMPATIBILITY_REVIEW', 'Compatibility Review'), ('WAITING_CONSENT', 'Waiting for Consent'), ('BOTH_ACCEPTED', 'Both Accepted'), ('APPROVED_ASSIGNED', 'Approved & Assigned'), ('ACTIVE', 'Active'), ('WAITLISTED', 'Waitlisted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=30),
        ),
        migrations.CreateModel(
            name='BookingConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(choices=[('PENDING', 'Pending Response'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('user_responded_at', models.DateTimeField(blank=True, null=True)),
                ('roommate_status', models.CharField(choices=[('PENDING', 'Pending Response'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('roommate_responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Consent expires after 24 hours if not accepted')),
                ('user_notified_at', models.DateTimeField(blank=True, null=True)),
                ('roommate_notified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notified_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_record', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking Consent',
                'verbose_name_plural': 'Booking Consents',
                'db_table': 'booking_consents',
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_room_number', models.CharField(help_text='e.g., D-204, Unit 5B', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('moved_in_date', models.DateField(blank=True, null=True)),
                ('moved_out_date', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_roommate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommate_assignments', to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignment', to='bookings.booking')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.roomtype')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.unittype')),
            ],
            options={
                'verbose_name': 'Room Assignment',
                'verbose_name_plural': 'Room Assignments',
                'db_table': 'room_assignments',
            },
        ),
        migrations.CreateModel(
            name='BookingStatusTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('triggered_by_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why the status changed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='bookings.booking')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Timeline Entry',
                'verbose_name_plural': 'Booking Timeline Entries',
                'db_table': 'booking_timeline',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='booking_tim_booking_2c2955_idx')],
            },
        ),
    ]
