# Generated by Django 6.0.6 on 2026-06-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_consent_timeout_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes on approval/rejection'),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_room',
            field=models.CharField(blank=True, help_text='e.g., D-204, Unit 5B', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_refund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='flags',
            field=models.JSONField(blank=True, default=list, help_text='Any issues/concerns'),
        ),
        migrations.AddField(
            model_name='booking',
            name='matching_timestamp',
            field=models.DateTimeField(blank=True, help_text='When compatibility was calculated', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='occupancy',
            field=models.PositiveIntegerField(blank=True, help_text='How many share this room', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Booking schema version'),
        ),
    ]
