# Generated by Django 6.0.6 on 2026-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_admin_approval_timestamp_booking_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='roommate_consent_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address when consent given', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='soft_lock_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the soft-lock on the slot expires', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_consent_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address when consent given', null=True),
        ),
    ]
