# Generated by Django 6.0.6 on 2026-06-21 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_visitrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot_hold_expires_at',
            field=models.DateTimeField(blank=True, help_text='6 hour slot hold after rejection', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='temp_cancel_expires_at',
            field=models.DateTimeField(blank=True, help_text='24 hour window to reinstate', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated (Soft Locked)'), ('UNDER_REVIEW', 'Under Review'), ('ASSIGNED_AWAITING', 'Assigned - Awaiting Roommate'), ('CONFIRMED_ASSIGNED', 'Confirmed and Assigned'), ('TEMPORARILY_CANCELLED', 'Temporarily Cancelled'), ('PERMANENTLY_CANCELLED', 'Permanently Cancelled'), ('ACTIVE', 'Active'), ('WAITLISTED', 'Waitlisted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='INITIATED', max_length=30),
        ),
        migrations.CreateModel(
            name='ConflictReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('NOISE', 'Noise'), ('CLEANLINESS', 'Cleanliness'), ('VISITORS', 'Visitors'), ('ITEMS', 'Items/Appliances'), ('PERSONAL', 'Personal Conflict'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('attempted_direct_resolution', models.BooleanField(default=False)),
                ('preferred_resolution', models.CharField(choices=[('MEDIATION', 'Mediation'), ('TRANSFER', 'Room Transfer'), ('LEASE_REVIEW', 'Lease Review'), ('ADMIN_CONTACT', 'Admin Contact')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_conflicts', to=settings.AUTH_USER_MODEL)),
                ('room_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_reports', to='bookings.roomassignment')),
            ],
            options={
                'db_table': 'conflict_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomSetupDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ELECTRICAL', 'Electrical Appliance'), ('FURNITURE', 'Furniture'), ('PERSONAL', 'Personal Equipment'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('consumption_level', models.CharField(choices=[('HIGH', 'High Consumption'), ('MEDIUM', 'Medium Consumption'), ('LOW', 'Low Consumption'), ('NONE', 'Not Applicable')], default='NONE', max_length=20)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flagged if violates property house rules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='bookings.roomassignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Setup Declaration',
                'verbose_name_plural': 'Room Setup Declarations',
                'db_table': 'room_setup_declarations',
            },
        ),
    ]
