# Generated by Django 6.0.6 on 2026-06-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_slot_hold_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='house_rules_acknowledged',
            field=models.BooleanField(default=False, help_text='User acknowledged property prohibited items/rules'),
        ),
    ]
