# Generated by Django 6.0.6 on 2026-06-21 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_house_rules_acknowledged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.roomassignment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Message',
                'verbose_name_plural': 'Room Messages',
                'db_table': 'room_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
