# Generated by Django 6.0.6 on 2026-06-21 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_notification_notification_type_and_more'),
        ('bookings', '0013_roommessage'),
        ('properties', '0005_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomassignment',
            name='assigned_room_number',
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='assigned_room',
            field=models.ForeignKey(help_text='The physical room assigned', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='properties.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='assigned_room',
            field=models.ForeignKey(blank=True, help_text='Physical room assigned to this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentative_bookings', to='properties.room'),
        ),
        migrations.CreateModel(
            name='LifestyleProfileLockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked'), ('ADMIN_UNLOCK_REQUESTED', 'Admin Unlock Requested'), ('ADMIN_UNLOCK_APPROVED', 'Admin Unlock Approved'), ('ADMIN_UNLOCK_DENIED', 'Admin Unlock Denied')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifestyle_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_logs', to='accounts.lifestyleprofile')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_lock_actions', to=settings.AUTH_USER_MODEL)),
                ('triggered_by_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_lock_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lifestyle Profile Lock Log',
                'verbose_name_plural': 'Lifestyle Profile Lock Logs',
                'db_table': 'lifestyle_lock_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
