# Generated by Django 6.0.6 on 2026-06-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_remove_roomassignment_assigned_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Has the 36-hour reminder been sent?'),
        ),
    ]
