# Generated by Django 6.0.6 on 2026-06-21 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_booking_reminder_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('high_priority_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('medium_priority_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('low_priority_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alignment_summary', models.TextField(blank=True)),
                ('difference_summary', models.TextField(blank=True)),
                ('routing_decision', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_scores', to='bookings.booking')),
                ('roommate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_compatibility_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compatibility Score',
                'verbose_name_plural': 'Compatibility Scores',
                'db_table': 'compatibility_scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
