# Generated by Django 6.0.6 on 2026-06-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_roomassignment_multi_occupant_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='billing_model',
            field=models.CharField(blank=True, choices=[('SEMESTER_BASED', 'Semester-Based'), ('MONTHLY_BASED', 'Monthly-Based'), ('ANNUAL_BASED', 'Annual-Based'), ('ACADEMIC_YEAR', 'Academic Year')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_months',
            field=models.PositiveIntegerField(blank=True, help_text='Number of months for Monthly-Based', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_semesters',
            field=models.PositiveIntegerField(blank=True, help_text='Number of semesters (1-3) for Semester-Based or Academic Year', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_years',
            field=models.PositiveIntegerField(blank=True, help_text='Number of years (1 or 2) for Annual-Based', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='semester_structure',
            field=models.CharField(blank=True, choices=[('CONTINUOUS_STAY', 'Continuous Stay (34 consecutive weeks)'), ('SPLIT_STAY', 'Split Stay with Vacation Gap')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vacation_gap_end',
            field=models.DateField(blank=True, help_text='Vacation gap end date for split stay', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vacation_gap_start',
            field=models.DateField(blank=True, help_text='Vacation gap start date for split stay', null=True),
        ),
    ]
