# Generated by Django 6.0.6 on 2026-06-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_booking_billing_model_booking_num_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='grace_period_end',
            field=models.DateField(blank=True, help_text='Grace period end date', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='grace_period_start',
            field=models.DateField(blank=True, help_text='Grace period start date', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='overstay_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Accumulated overstay charges', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='overstay_start_date',
            field=models.DateField(blank=True, help_text='Date overstay began', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_status',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'AVAILABLE'), ('SOFT_LOCKED', 'SOFT_LOCKED'), ('OCCUPIED', 'OCCUPIED'), ('FULLY_OCCUPIED', 'FULLY_OCCUPIED'), ('VACATION_RESERVE', 'VACATION_RESERVE'), ('PRACTICAL_CHECKOUT', 'PRACTICAL_CHECKOUT'), ('GRACE_PERIOD', 'GRACE_PERIOD'), ('OVERSTAY', 'OVERSTAY'), ('MAINTENANCE', 'MAINTENANCE'), ('ARCHIVED', 'ARCHIVED')], default='AVAILABLE', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vacation_reserve_active',
            field=models.BooleanField(default=False, help_text='Whether vacation reserve is currently active'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vacation_reserve_end',
            field=models.DateField(blank=True, help_text='Vacation reserve end date', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vacation_reserve_start',
            field=models.DateField(blank=True, help_text='Vacation reserve start date', null=True),
        ),
    ]
