# Generated by Django 6.0.6 on 2026-06-26 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_booking_grace_period_end_booking_grace_period_start_and_more'),
        ('properties', '0009_alter_room_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_model', models.CharField(choices=[('SEMESTER_BASED', 'Semester-Based'), ('MONTHLY_BASED', 'Monthly-Based'), ('ANNUAL_BASED', 'Annual-Based'), ('ACADEMIC_YEAR', 'Academic Year')], max_length=50)),
                ('num_semesters', models.IntegerField(blank=True, null=True)),
                ('num_months', models.IntegerField(blank=True, null=True)),
                ('num_years', models.IntegerField(blank=True, null=True)),
                ('semester_structure', models.CharField(blank=True, choices=[('CONTINUOUS_STAY', 'Continuous Stay (34 consecutive weeks)'), ('SPLIT_STAY', 'Split Stay with Vacation Gap')], max_length=50, null=True)),
                ('vacation_gap_start', models.DateField(blank=True, null=True)),
                ('vacation_gap_end', models.DateField(blank=True, null=True)),
                ('semester1_end', models.DateField(blank=True, null=True)),
                ('semester2_start', models.DateField(blank=True, null=True)),
                ('semester2_end', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_duration_weeks', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_allocation', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Billing Allocation',
                'verbose_name_plural': 'Billing Allocations',
                'db_table': 'billing_allocations',
            },
        ),
        migrations.CreateModel(
            name='BookingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_model', models.CharField(blank=True, choices=[('SEMESTER_BASED', 'Semester-Based'), ('MONTHLY_BASED', 'Monthly-Based'), ('ANNUAL_BASED', 'Annual-Based'), ('ACADEMIC_YEAR', 'Academic Year')], max_length=50, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('num_semesters', models.IntegerField(blank=True, null=True)),
                ('num_months', models.IntegerField(blank=True, null=True)),
                ('num_years', models.IntegerField(blank=True, null=True)),
                ('semester_structure', models.CharField(blank=True, choices=[('CONTINUOUS_STAY', 'Continuous Stay (34 consecutive weeks)'), ('SPLIT_STAY', 'Split Stay with Vacation Gap')], max_length=50, null=True)),
                ('vacation_gap_end', models.DateField(blank=True, null=True)),
                ('temporary_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned'), ('CONVERTED', 'Converted to Booking')], default='IN_PROGRESS', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft', to='bookings.booking')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_drafts', to='properties.property')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.roomtype')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.unittype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Draft',
                'verbose_name_plural': 'Booking Drafts',
                'db_table': 'booking_drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_consent', models.BooleanField(default=False)),
                ('user_consent_date', models.DateTimeField(blank=True, null=True)),
                ('user_consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('roommate_consent', models.BooleanField(default=False)),
                ('roommate_consent_date', models.DateTimeField(blank=True, null=True)),
                ('roommate_consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_deadline', models.DateTimeField(blank=True, null=True)),
                ('consent_status', models.CharField(choices=[('PENDING', 'Pending'), ('USER_CONSENTED', 'User Consented'), ('ROOMMATE_CONSENTED', 'Roommate Consented'), ('BOTH_CONSENTED', 'Both Consented'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_consent_record', to='bookings.booking')),
                ('roommate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Record',
                'verbose_name_plural': 'Consent Records',
                'db_table': 'consent_records',
            },
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy_type', models.CharField(blank=True, max_length=20, null=True)),
                ('slot_number', models.IntegerField(blank=True, null=True)),
                ('allocation_status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONFIRMED', 'Confirmed'), ('RELEASED', 'Released')], default='RESERVED', max_length=20)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.room')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocation', to='bookings.booking')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.roomtype')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.unittype')),
            ],
            options={
                'verbose_name': 'Room Allocation',
                'verbose_name_plural': 'Room Allocations',
                'db_table': 'room_allocations',
            },
        ),
    ]
