# Generated by Django 6.0.6 on 2026-06-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_booking_flow_new_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='houserulesacknowledgment',
            new_name='house_rules_user_id_207809_idx',
            old_name='idx_user_property_ack',
        ),
        migrations.RenameIndex(
            model_name='houserulesacknowledgment',
            new_name='house_rules_session_cb635a_idx',
            old_name='idx_session_ack',
        ),
    ]
