# Generated by Django 6.0.6 on 2026-06-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_rename_idx_user_property_ack_house_rules_user_id_207809_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lifestyle_progress',
            field=models.JSONField(blank=True, help_text='Partial lifestyle questionnaire answers', null=True),
        ),
    ]
