# Generated by Django 6.0.6 on 2026-06-27 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_booking_compatibility_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='num_months',
            new_name='months_selected',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='num_semesters',
            new_name='semesters_selected',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='num_years',
            new_name='years_selected',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='admin_approval_timestamp',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_refund',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='consent_timeout_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='overstay_charges',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='overstay_start_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='roommate_consent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='roommate_consent_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='roommate_consent_ip',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='semester_structure',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_consent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_consent_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_consent_ip',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vacation_gap_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vacation_gap_start',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='vacation_reserve_active',
        ),
        migrations.AddField(
            model_name='booking',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When admin reviewed this booking', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='admin_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_initiated_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('system', 'System'), ('admin', 'Admin')], help_text='Who initiated the cancellation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='consent_rejected_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when consent was rejected', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='consent_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='not_required', help_text='Consent status', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='GHS', help_text='Currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Total duration in days', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='lifestyle_profile_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of lifestyle profile used', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='lifestyle_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When lifestyle questionnaire was submitted', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='matched_with_booking_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the booking this is matched with', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='overstay_accrued',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total overstay charges accrued', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='overstay_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily overstay charge rate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='overstay_start',
            field=models.DateTimeField(blank=True, help_text='Timestamp when overstay began', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='permanently_cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when permanently cancelled', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per billing unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Refund amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='not_applicable', help_text='Refund status', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='reinstated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when booking was reinstated', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_period',
            field=models.CharField(blank=True, choices=[('semester', 'Semester'), ('monthly', 'Monthly'), ('annual', 'Annual')], help_text='Rental period type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='semester_2_cancelled',
            field=models.BooleanField(default=False, help_text='Whether Semester 2 was cancelled'),
        ),
        migrations.AddField(
            model_name='booking',
            name='semester_2_end_date',
            field=models.DateField(blank=True, help_text='Semester 2 end date', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='semester_2_refund_issued',
            field=models.BooleanField(default=False, help_text='Whether refund was issued for cancelled S2'),
        ),
        migrations.AddField(
            model_name='booking',
            name='semester_2_start_date',
            field=models.DateField(blank=True, help_text='Semester 2 start date for split stays', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='soft_lock_released',
            field=models.BooleanField(default=False, help_text='Whether the soft lock has been released'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stay_structure',
            field=models.CharField(blank=True, choices=[('CONTINUOUS_STAY', 'Continuous Stay (34 consecutive weeks)'), ('SPLIT_STAY', 'Split Stay with Vacation Gap')], help_text='Continuous or Split stay', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total booking price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, help_text='Reason for cancellation', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated (Soft Locked)'), ('LIFESTYLE_PENDING', 'Lifestyle Pending'), ('LIFESTYLE_COMPLETE', 'Lifestyle Complete'), ('AWAITING_COMPATIBILITY', 'Awaiting Compatibility'), ('AUTO_ASSIGNED', 'Auto Assigned'), ('CONSENT_PENDING', 'Consent Pending'), ('CONSENT_ACCEPTED', 'Consent Accepted'), ('TEMPORARILY_CANCELLED', 'Temporarily Cancelled'), ('REINSTATED', 'Reinstated'), ('ADMIN_PENDING', 'Admin Pending'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('VACATION_RESERVE', 'Vacation Reserve'), ('GRACE_PERIOD', 'Grace Period'), ('COMPLETED', 'Completed'), ('PERMANENTLY_CANCELLED', 'Permanently Cancelled'), ('EXPIRED', 'Expired')], default='INITIATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
