# Generated by Django 6.0.6 on 2026-07-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0028_adminbookingqueue_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated (Soft Locked)'), ('LIFESTYLE_PENDING', 'Lifestyle Pending'), ('LIFESTYLE_COMPLETE', 'Lifestyle Complete'), ('AWAITING_COMPATIBILITY', 'Awaiting Compatibility'), ('AUTO_ASSIGNED', 'Auto Assigned'), ('CONSENT_PENDING', 'Consent Pending'), ('CONSENT_ACCEPTED', 'Consent Accepted'), ('TEMPORARILY_CANCELLED', 'Temporarily Cancelled'), ('REINSTATED', 'Reinstated'), ('ADMIN_PENDING', 'Admin Pending'), ('PAYMENT_REQUIRED', 'Payment Required'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('PAYMENT_PENDING_VERIFICATION', 'Payment Pending Verification'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_EXPIRED', 'Payment Expired'), ('PAYMENT_COMPLETE', 'Payment Complete'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('VACATION_RESERVE', 'Vacation Reserve'), ('GRACE_PERIOD', 'Grace Period'), ('COMPLETED', 'Completed'), ('PERMANENTLY_CANCELLED', 'Permanently Cancelled'), ('EXPIRED', 'Expired'), ('ASSIGNED_AWAITING', 'Assigned - Awaiting Roommate'), ('CONFIRMED_ASSIGNED', 'Confirmed and Assigned'), ('UNDER_REVIEW', 'Under Review'), ('WAITING_CONSENT', 'Waiting Consent'), ('COMPATIBILITY_REVIEW', 'Compatibility Review'), ('WAITLISTED', 'Waitlisted'), ('REJECTED', 'Rejected')], default='INITIATED', max_length=30),
        ),
    ]
