# Generated by Django 6.0.7 on 2026-07-21 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_alter_booking_status'),
        ('properties', '0012_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='properties.room'),
        ),
    ]
